### ISSUE TITLE
`sed` illegal option error when running `./provision.sh`

### ISSUE THREAD

**Issue by ycsh-w** [meonkeys/shb#1]
Hi!

First of all, thank you for all the great work!

I am trying to follow the steps and I am encountering this:

```
❯ ./provision.sh
sed: illegal option -- -
usage: sed script [-Ealnru] [-i extension] [file ...]
        sed [-Ealnu] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```

Might be some bug in the script?

**Comment by meonkeys** [comment]
Ah dang, yep. `provision.sh` assumes GNU sed. Sorry, I just broke that when I added something to make sure the right version of Ansible is installed (in 35d204d3e0b8486a9ff7edf14e08eda7ad768d90)! I'll just revert it for now, hopefully that'll get `provision.sh` working for you again. Perhaps that sed command can be made more compatible with more versions of sed.

**Comment by meonkeys** [comment]
Do you know how to tweak that sed line to make it compatible with yours? Maybe it's BSD sed if it's on macOS.

**Comment by meonkeys** [comment]
No worries, I think I got it. Please try updating your clone, see if it works now.

**Comment by meonkeys** [comment]
Fixed in 35d204d3e0b8486a9ff7edf14e08eda7ad768d90, hopefully.

**Comment by meonkeys** [comment]
Uff, yeah, that was super naive of me to think `sort -V` would be portable (I bet that's what's breaking).

I know how to fix that bug in the version check for macOS, but it looks like you'll still need a more recent Ansible core (note the mention of version `2.16.1` in `provision.sh`). Will you figure out how to upgrade Ansible core, and I'll fix the version check for macOS in `provision.sh`?

**Comment by meonkeys** [comment]
Whoops, indeed, my bad. Does `provision.sh` get farther along for you now?

**Comment by meonkeys** [comment]
Sure thing. I appreciate your bug report.
