### ISSUE TITLE
"Failed to set time zone: Invalid or not installed time zone 'Zulu'"

### ISSUE THREAD

**Issue by a-w-1806** [meonkeys/shb#3]
It seems like it is not a valid default value.

```
fatal: [mario_server]: FAILED! => {"changed": true, "cmd": ["timedatectl", "set-timezone", "Zulu"], "delta": "0:00:00.032956", "end": "2024-06-26 00:11:34.900010", "msg": "non-zero return code", "rc": 1, "start": "2024-06-26 00:11:34.867054", "stderr": "Failed to set time zone: Invalid or not installed time zone 'Zulu'", "stderr_lines": ["Failed to set time zone: Invalid or not installed time zone 'Zulu'"], "stdout": "", "stdout_lines": []}
```

FYI, it takes about 18 mins for me to reach and fail at this step. I am running on macOS with a VM.

**Comment by meonkeys** [comment]
Good catch! Thank you. Yes, that should be `Etc/Zulu`. I'll fix and push.

> FYI, it takes about 18 mins for me to reach and fail at this step.

That feels like a really long time. Does the VM have sufficient compute, memory, and disk allocated?

**Comment by meonkeys** [comment]
> I am on a M2 Mac Mini and I have 2 cores and 4GB for the VM. Sounds like should be enough for getting started?

Sounds like plenty of resources, yep. I'm wondering if that slowdown is an architecture mismatch? M2 uses the arm instruction set, so we should make sure you're all matched up there. Again, I'm not an expert here, just guessing:

* try using an ARM build of 24.04 server from https://ubuntu.com/download/server/arm
* make sure the VM is configured for ARM

You may have to reinstall the OS but it will be worth it if it gets your 6-18min provision down to 5-15 sec.

**Comment by meonkeys** [comment]
I moved the performance issue to #5
