### ISSUE TITLE
Changing `MARIO_DOMAIN_NAME` after the first `./provision.sh` run

### ISSUE THREAD

**Issue by ycsh-w** [meonkeys/shb#4]
Yeah it's until I see a later chapter of duckdns then I decide to get one 😄  So the first run is with the default value of `example.com`.

When I run `dc traefik logs -f` and try to access this in my browser I see: `Contact emails @example.com are forbidden`, even though I already changed this value to a duck dns.

Could you please advise what should I do? Thanks!

**Comment by meonkeys** [comment]
This smells like an issue with a different config variable: `DNS_RESOLVER_EMAIL`. Make sure that is a real, working email address and let me know if that works.

Traefik runs Let's Encrypt and I bet Let's Encrypt is rejecting `fixme.dns.email@example.com` or whatever.

**Comment by meonkeys** [comment]
Please make sure you've got the most recent code, too. I've made a few fixes based on comments from other readers. You might have to manually merge in changes to comments from `template/config` so you don't clobber the correct/actual values of your configuration variables.

Also FWIW, I have made this same mistake changing `template/config` when I already also have a `config` file... :facepalm:
